spring:
  application:
    name: kafka-example-app
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: test
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
app:
  kafka:
    kafkaMessageTopic: "message-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
